# Generated by Django 5.1.2 on 2024-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('idsanPham', models.IntegerField(primary_key=True, serialize=False)),
                ('tenSanPham', models.CharField(max_length=255)),
                ('hinhAnh', models.CharField(max_length=255)),
                ('maTheLoai', models.CharField(max_length=50)),
            ],
        ),
    ]
